---
name: 'go-lint'
description: 'go-lint by Pipeline Components'
author: 'Robbert Müller <spam.me@grols.ch>'
branding:
  icon: 'flag'
  color: 'green'
inputs:
  directory:
    description: 'Directory to lint'
    required: false
    default: "./..."
  options:
    description: 'Additional options'
    required: false
    default: '--set_exit_status'
runs:
  using: 'docker'
  image: docker://pipelinecomponents/go-lint
  args:
    - golint
    - '${{ inputs.options }}'
    - '${{ inputs.directory }}'
